---
title: "R Notebook"
output: html_notebook
---

```{r}
# calling function TPFA for example 01

library(rMRST)

# grid <- Grid$new()
Grid <- makeGrid(8, 8, 1)

Grid$Nx = 8; Grid$hx = 1 / Grid$Nx
Grid$Ny = 8; Grid$hy = 1 / Grid$Ny
Grid$Nz = 1; Grid$hz = 1 / Grid$Nz

Grid$K = ones(3, Grid$Nx, Grid$Ny);
N <-  Grid$Nx * Grid$Ny * Grid$Nz

q <- zeros(N, 1)
q[c(N, 1)] = c(1, -1)


K = Grid$K

# call function TPFA
tpfa <- TPFA(Grid, K, q)   # returns a list of P, V
names(tpfa)

```


```{r fig.asp=1}
# Plot of pressure vs (x,y)
P <- tpfa$P

Nx = seq(0, 1, length.out = Grid$Nx)
Ny = seq(0, 1, length.out = Grid$Ny)

P <- matrix(P, nrow=8, ncol=8)
filled.contour(x = Nx, y = Ny, z = P, color = rainbow, 
               key.axes = axis(4, seq(0, 3, by = 0.2)))
```

```{r}
# Flux in x
Nx = seq(0, 1, length.out = Grid$Nx)
Ny = seq(0, 1, length.out = Grid$Ny+1)


Vx <- matrix(tpfa$V$x, nrow=9, ncol=8)

filled.contour(x = Ny, y = Nx, z = Vx, color = rainbow )
               # key.axes = axis(4, seq(0, 3, by = 0.2)))

```


```{r}
x <- -6:16
z <- outer(x, sqrt(abs(x)), FUN = "/")
length(x)
dim(z)
```

```{r}
require(grDevices) # for colours
filled.contour(volcano, color = terrain.colors, asp = 1) # simple

x <- 10*1:nrow(volcano)
y <- 10*1:ncol(volcano)
filled.contour(x, y, volcano, color = terrain.colors,
    plot.title = title(main = "The Topography of Maunga Whau",
    xlab = "Meters North", ylab = "Meters West"),
    plot.axes = { axis(1, seq(100, 800, by = 100))
                  axis(2, seq(100, 600, by = 100)) },
    key.title = title(main = "Height\n(meters)"),
    key.axes = axis(4, seq(90, 190, by = 10)))  # maybe also asp = 1
mtext(paste("filled.contour(.) from", R.version.string),
      side = 1, line = 4, adj = 1, cex = .66)

# Annotating a filled contour plot
a <- expand.grid(1:20, 1:20)
b <- matrix(a[,1] + a[,2], 20)
filled.contour(x = 1:20, y = 1:20, z = b,
               plot.axes = { axis(1); axis(2); points(10, 10) })

## Persian Rug Art:
x <- y <- seq(-4*pi, 4*pi, len = 27)
r <- sqrt(outer(x^2, y^2, "+"))
filled.contour(cos(r^2)*exp(-r/(2*pi)), axes = FALSE)
## rather, the key *should* be labeled:
filled.contour(cos(r^2)*exp(-r/(2*pi)), frame.plot = FALSE,
               plot.axes = {})

```


```{r}
require(grDevices) # for colours
x <- -6:16
op <- par(mfrow = c(2, 2))
contour(outer(x, x), method = "edge", vfont = c("sans serif", "plain"))
z <- outer(x, sqrt(abs(x)), FUN = "/")
image(x, x, z)
contour(x, x, z, col = "pink", add = TRUE, method = "edge",
        vfont = c("sans serif", "plain"))
contour(x, x, z, ylim = c(1, 6), method = "simple", labcex = 1,
        xlab = quote(x[1]), ylab = quote(x[2]))
contour(x, x, z, ylim = c(-6, 6), nlev = 20, lty = 2, method = "simple",
        main = "20 levels; \"simple\" labelling method")
par(op)

## Persian Rug Art:
x <- y <- seq(-4*pi, 4*pi, len = 27)
r <- sqrt(outer(x^2, y^2, "+"))
opar <- par(mfrow = c(2, 2), mar = rep(0, 4))
for(f in pi^(0:3))
  contour(cos(r^2)*exp(-r/f),
          drawlabels = FALSE, axes = FALSE, frame = TRUE)

rx <- range(x <- 10*1:nrow(volcano))
ry <- range(y <- 10*1:ncol(volcano))
ry <- ry + c(-1, 1) * (diff(rx) - diff(ry))/2
tcol <- terrain.colors(12)
par(opar); opar <- par(pty = "s", bg = "lightcyan")
plot(x = 0, y = 0, type = "n", xlim = rx, ylim = ry, xlab = "", ylab = "")
u <- par("usr")
rect(u[1], u[3], u[2], u[4], col = tcol[8], border = "red")
contour(x, y, volcano, col = tcol[2], lty = "solid", add = TRUE,
        vfont = c("sans serif", "plain"))
title("A Topographic Map of Maunga Whau", font = 4)
abline(h = 200*0:4, v = 200*0:4, col = "lightgray", lty = 2, lwd = 0.1)

## contourLines produces the same contour lines as contour
plot(x = 0, y = 0, type = "n", xlim = rx, ylim = ry, xlab = "", ylab = "")
u <- par("usr")
rect(u[1], u[3], u[2], u[4], col = tcol[8], border = "red")
contour(x, y, volcano, col = tcol[1], lty = "solid", add = TRUE,
        vfont = c("sans serif", "plain"))
line.list <- contourLines(x, y, volcano)
invisible(lapply(line.list, lines, lwd=3, col=adjustcolor(2, .3)))
par(opar)
```

```{r}
library(asbio)

X1 <-sort(rnorm(100))
X2 <-rexp(100)
Y <-rgamma(100, 1, 2)
loess.surf(Y, cbind(X1,X2))
```

