---
title: "MRST - Example 01.2"
output: html_notebook
---

## 8x8x1 grid

```{r fig.asp=1}
# testing 3D convolution from dcemriS4 package
# calling function TPFA for example 01.2

library(rMRST)
library(dcemriS4)

Grid <- makeGrid()

# Grid 8x8x1
Grid$Nx =  8; Grid$hx = 1 / Grid$Nx
Grid$Ny =  8; Grid$hy = 1 / Grid$Ny
Grid$Nz =  1; Grid$hz = 1 / Grid$Nz

#  Grid.K=exp(5∗smooth3(smooth3(randn(3,Grid.Nx,Grid.Ny))));
# Permeabilities array 3x32x32
Grid$K = randn(3, Grid$Nx, Grid$Ny)

A = Grid$K
B = Grid$K
tcenter = findCenter(ifelse(A > 0, TRUE, FALSE))
out <- convFFT(A, B, tcenter)

# image only plots matrices. remove the 1st dimension of the permeabilities
par(mfrow=c(2, 2))  ## graphic output
image(B[1,,], col=oro.nifti::tim.colors(), main="Template")
image(A[1,,], col=oro.nifti::tim.colors(), main="Target")
image(out[1,,], col=oro.nifti::tim.colors(), main="Output")
```

## 32x32x1 grid

```{r fig.asp=1}
# testing 3D convolution from dcemriS4 package
# calling function TPFA for example 01.2

library(rMRST)
library(dcemriS4)

Grid <- makeGrid()

# Grid 32x32x1
Grid$Nx = 32; Grid$hx = 1 / Grid$Nx
Grid$Ny = 32; Grid$hy = 1 / Grid$Ny
Grid$Nz =  1; Grid$hz = 1 / Grid$Nz

#  Grid.K=exp(5∗smooth3(smooth3(randn(3,Grid.Nx,Grid.Ny))));
# Permeabilities array 3x32x32
Grid$K = randn(3, Grid$Nx, Grid$Ny)
dim(Grid$K)

A = Grid$K
B = Grid$K
tcenter = findCenter(ifelse(A > 0, TRUE, FALSE))
out <- convFFT(A, B, tcenter)
dim(out)

# image only plots matrices. remove the 1st dimension of the permeabilities
par(mfrow=c(2, 2))  ## graphic output
image(B[1,,], col=oro.nifti::tim.colors(), main="Template")
image(A[1,,], col=oro.nifti::tim.colors(), main="Target")
image(out[1,,], col=oro.nifti::tim.colors(), main="Output")
```




```{r}
# calling function TPFA for example 01.2

library(rMRST)

Grid <- makeGrid()

Grid$Nx = 32; Grid$hx = 1 / Grid$Nx
Grid$Ny = 32; Grid$hy = 1 / Grid$Ny
Grid$Nz = 1; Grid$hz = 1 / Grid$Nz

#  Grid.K=exp(5∗smooth3(smooth3(randn(3,Grid.Nx,Grid.Ny))));
Grid$K = randn(3, Grid$Nx, Grid$Ny)
N <-  Grid$Nx * Grid$Ny * Grid$Nz

q <- zeros(N, 1)
q[c(N, 1)] = c(1, -1)


K = Grid$K

# call function TPFA
tpfa <- TPFA(Grid, K, q)   # returns a list of P, V
names(tpfa)

```


```{r fig.asp=1}
# Plot of pressure vs (x,y)
P <- tpfa$P

Nx = seq(0, 1, length.out = Grid$Nx)
Ny = seq(0, 1, length.out = Grid$Ny)

P <- matrix(P, nrow=Grid$Nx, ncol=Grid$Ny)
filled.contour(x = Nx, y = Ny, z = P, color = rainbow, 
               key.axes = axis(4, seq(0, 3, by = 0.2)))
```

```{r}
# Flux in x
Nx = seq(0, 1, length.out = Grid$Nx)
Ny = seq(0, 1, length.out = Grid$Ny+1)


Vx <- matrix(tpfa$V$x, nrow=9, ncol=8)

filled.contour(x = Ny, y = Nx, z = Vx, color = rainbow )
               # key.axes = axis(4, seq(0, 3, by = 0.2)))

```


```{r}
x <- -6:16
z <- outer(x, sqrt(abs(x)), FUN = "/")
length(x)
dim(z)
```




