---
title: "R Notebook"
output: html_notebook
---

```{r}
padreplicate <- function(a, padSize) {
    # Pad an array by replicating values.
    numDims <- length(padSize)
    idx <- vector("list", numDims)
    for (k in 1:numDims) {
        M <-  dim(a)[k]       # 32
        # onesVector <-  ones(1, padSize[k])
        onesVector <-  matrix(1, 1, padSize[k])
        idx[[k]] <- c(onesVector, 1:M, M * onesVector)
        print(idx[[k]])
    }
    do.call( `[`, c(list(a), idx)) 
}

# pad a matrix 4x3 with c(1,1)
set.seed(123456)
mx = matrix(sample.int(9, size = 9*100, replace = TRUE), nrow = 4, ncol = 3)
mx

padreplicate(mx, c(1,1))

```

```{r}
# this is the manual operation of modifying the original matrix
mx[c(1,1,2,3,4,4), c(1,1,2,3,3)]
# index of rows to duplicate: c(1,1,2,3,4,4)
# index of cols to duplicate: c(1,1,2,3,3)
```


```{r}
set.seed(123456)
ar = array(sample.int(9, size = 9*100, replace = TRUE), dim = c(3, 3, 1))
ar
padreplicate(ar, c(1,1,1))
```


```{r}
## Example with different lengths for each call
z <- array(1:24, dim = 2:4)
zseq <- apply(z, 1:2, function(x) seq_len(max(x)))
zseq         ## a 2 x 3 matrix
typeof(zseq) ## list
dim(zseq) ## 2 3
zseq[1,]
apply(z, 3, function(x) seq_len(max(x)))
# a list without a dim attribute

cat("MARGIN=2:3\n")
apply(z, 2:3, function(x) seq_len(max(x)))
```


# for vectors

```{r}
li = list(c(3,4))
li
v <- c(9,8,7,6,5,4)
v[unlist(li)]
```

```{r}
library(rMRST)
set.seed(123456)
arr = array(sample.int(9, size = 9*100, replace = TRUE), dim = c(3, 4, 2))
# arr

padSize = c(1,1)
length(padSize)
rMRST:::padreplicate(arr, padSize)
```

```{r}
# pad a matrix with c(1,1)
library(rMRST)
set.seed(123456)
mx = matrix(sample.int(9, size = 9*100, replace = TRUE), nrow = 4, ncol = 3)
mx

rMRST:::padreplicate(mx, c(1,1))
```


```{r}
# # pad a matrix with c(2,2)
library(rMRST)
set.seed(123456)
mx = matrix(sample.int(9, size = 9*100, replace = TRUE), nrow = 3, ncol = 4)
mx

rMRST:::padreplicate(mx, c(2,2))
```



```{r}
li = list(c(3,4), c(7, 9))
m[unlist(li)]
```

